Fixed compiler errors and warnings after the transition to ACTS v40.0.0
Error: Reference to the obsolete CurvilinearTrackParameters
Warnings: Unused private variable and lambda capture